### PR TITLE
Fix: linux apt installation

### PR DESCRIPTION
**Pull request by maxjendrall**

### CODE REVIEW

**Comment by mwarning** [comment]
Thanks!
I think `apt` is the more user friendly and commonly accepted command. Could you change that?

**Comment by mwarning** [comment]
Thanks!
I think `apt` is the more user friendly and commonly accepted command. Could you change that?

**Comment by toorusr** [comment]
Yeah, you are right, I will change it right away

**Comment by toorusr** [comment]
Fixed it @mwarning

**Comment by mwarning** [comment]
+1

**Pull request merged**
